---
-
  hosts: linux
  user: root
  gather_facts: True
  vars:
    motd_centos: "Welcome to CentOS Linux - Ansible o/\n"
    motd_ubuntu: "Welcome to Ubuntu Linux - Ansible o/\n"
  tasks:
    - name: Configure a MOTD (Message of the day)
      copy:
        content: "{{ motd_centos }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "CentOS"
    - name: Configure a MOTD (Message of the day)
      copy:
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "Ubuntu"
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed
...
