---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
  hosts: linux
  vars_files:
    - vars/logos.yaml
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        state: latest
        update_cache: yes
      when: ansible_distribution == 'CentOS'
    - name: Install nginx
      package:
        name:
          - nginx
        state: latest
    - name: Restart nginx
      service: 
        name: nginx
        state: restarted
      notify: Check HTTP Service
    - name: Template index.html-base.j2 to index.html on target
      template:
        src: index.html-base.j2
        dest: "{{ nginx_root_location }}/index.html"
        mode: 0644
    - name: Override template index.html-ansible_managed.j2 to index.html on target
      template:
        src: index.html-ansible_managed.j2
        dest: "{{ nginx_root_location }}/index.html"
        mode: 0644
    - name: Override template index.html-logos.j2 to index.html on target
      template:
        src: index.html-logos.j2
        dest: "{{ nginx_root_location }}/index.html"
        mode: 0644
    - name: Override template index.html-easter_egg.j2 to index.html on target
      template:
        src: index.html-easter_egg.j2
        dest: "{{ nginx_root_location }}/index.html"
        mode: 0644
    - name: Install unzip
      package:
        name: unzip
        state: latest
    - name: Unarchive playbook stacker game
      unarchive:
        src: playbook_stacker.zip
        dest: "{{ nginx_root_location }}"
        mode: 0755
  handlers:
    - name: Check HTTP Service
      uri:
        url: http://{{ ansible_default_ipv4.address }}
        status_code: 200


  # Handlers: the list of handlers that are executed as a notify key from a task
...
